stages:
    - build

qt6:
    image: opensuse/tumbleweed
    stage: build
    before_script:
    - zypper in -y qt6-base-devel gcc-c++ make
    script:
    - qmake6 src
    - make -j2
    artifacts:
        name: qmtn-$CI_JOB_NAME
        expire_in: 4 week
        paths:
        - ./qmtn
qt5:
    image: debian:11
    stage: build
    before_script:
    - apt-get update
    - apt-get install -y g++ qtbase5-dev qtwebengine5-dev
    script:
    - qmake CONFIG+=use_webengine src
    - make -j2
    artifacts:
        name: qmtn-$CI_JOB_NAME
        expire_in: 4 week
        paths:
        - ./qmtn

