stages:
    - build

qt6:
    image: opensuse/tumbleweed
    stage: build
    before_script:
    - zypper in -y qt6-base-devel gcc-c++ make
    script:
    - qmake6 src
    - make -j2
    artifacts:
        name: qmtn-$CI_JOB_NAME
        expire_in: 4 week
        paths:
        - ./qmtn
qt5:
    image: centos:7
    stage: build
    before_script:
    - yum -y install gcc-c++ qt5-qtbase-devel make
    script:
    - qmake-qt5 src
    - make
    artifacts:
        name: qmtn-$CI_JOB_NAME
        expire_in: 4 week
        paths:
        - ./qmtn
